<?php

namespace Tebex\Webhook;

use ValueError;

/**
 * The validation webhook is sent to ensure we are not sending HTTP requests to URLs that are not expecting our webhooks.
 * Webhooks will not be sent to an endpoint unless it has been validated first.
 *
 * Upon receiving a validation webhook you must respond with a 200 OK response containing a JSON object that has an id property representing the validation webhook's ID, please see the example response below.
 */
class ValidationWebhook extends Webhook
{
    /**
     * Validates if the webhook originated from Tebex by checking IP header.
     *
     * It is always recommended to use REMOTE_ADDR as the client can spoof any HTTP headers ("HTTP_CLIENT_IP", "HTTP_X_FORWARDED_FOR")
     * to anything they want. This can lead to security vulnerabilities. If you use a proxy, it should be configured to replace the
     * REMOTE_ADDR header with the real remote address.
     *
     * In addition to validating IP, you should also use validateSignature() to authenticate the webhook.
     *
     * @param $ipHeaderName string The name of the header containing the requestor's IP
     * @return bool True if the request IP matches a Tebex IP
     */
    public function validateIp(string $ipHeaderName = "REMOTE_ADDR"): bool
    {
        if (!array_key_exists($ipHeaderName, $_SERVER)) {
            throw new ValueError("IP header not present: " . $ipHeaderName);
        }
        $requestIp = $_SERVER[$ipHeaderName];
        return $requestIp == "18.209.80.3" || $requestIp == "54.87.231.232";
    }

    /**
     * Compares the provided webhook signature to a calculated signature based on the signature's compact JSON.
     *
     * The signature is generated by SHA256 hashing the JSON body and then building a SHA256 HMAC with the body hash as
     * the data/content and your webhook secret as the key.
     *
     * @param $expectedSignature string   The signature received in the X-Signature header.
     * @param $webhookSecret string       The secret key for webhooks.
     * @return bool
     */
    public function validateSignature(string $expectedSignature, string $webhookSecret): bool
    {
        $calculatedSignature = hash_hmac('sha256', hash('sha256', $this->_encodedJson), $webhookSecret);
        return $expectedSignature === $calculatedSignature;
    }
}